version: 0.2

run-as: root
       
phases:
  install:
    # run-as: root
    commands:
      - command
      - command
    finally:
      - command
      - command
  pre_build:
    # run-as: root
    commands:
      - command
      - command
    finally:
      - command
      - command
  build:
    # run-as: root
    commands:
      - command
      - command
    finally:
      - command
      - command
  post_build:
    # run-as: root
    commands:
      - command
      - command
    finally:
      - command
      - command